### ISSUE TITLE
Role is returned as nil

### ISSUE THREAD

**Issue by wjdhamilton** [saturnflyer/surrounded#23]
Hello,

I have a very simple context set up with two roles as below:

     class ValidatingPostcodes
        extend Surrounded::Context

        require 'going_postal'

        keyword_initialize :country, :postcode

        trigger :validate do
           postcode.validate_postcode
        end

        role :postcode do
          def validate_postcode
            country_code = country.alpha_2 #country is nil
            if valid = GoingPostal.valid_postcode?(code, country_code)
              self.code = valid
            else
              errors.add(:code, "This is not a valid postcode for #{country_code}")
            end
          end
        end
      end

My tests fail when country.alpha_2 is called. I have checked that country is present at the time that the trigger is called, which it is, however it doesn't seem to have made it into the role. This error appears in both surrounded and surrounded-rails. 

I really it hope it isn't anything obvious, but I cannot see where things are going wrong!

Running on ruby 2.1.5 and rails 4.2.4

**Comment by saturnflyer** [comment]
@wjdhamilton does `postcode` already have a `country` accessor method?
`postcode` will only be able to implicitly access `country` if it does _not_ already have a method for that since Surrounded relies on `method_missing`

If that's the case, you could just change the `country` role in this context to some other name.
Or you might be able to define a `country` method in the `postcode` role to pull from the context object itself (although that changes the semantics of an existing method, which I'd prefer to avoid).

Let me know if this helps. I'm not sure if I have enough information to properly debug

**Comment by wjdhamilton** [comment]
Aaagh! I knew it was probably something simple. Oh I feel so stupid...
Thanks @saturnflyer , particularly for replying on a Sunday. 

PS Really enjoyed Clean Ruby!

**Comment by saturnflyer** [comment]
thanks! Seems like there should be an option to raise an error on name collisions.
