### ISSUE TITLE
Surrounded vs Casting

### ISSUE THREAD

**Issue by jonahx** [saturnflyer/surrounded#28]
Hey Jim, one more quick question.  I was checking out Casting as well, and thinking about when you'd use that vs Surrounded.  Here's what I came up with.  Can you let me know if this rings true for you, or if you have anything to add:

1. DCI style programming can be done with either Surrounded or Casting
2. Casting is a "smaller buyin" approach, in that you don't have to touch your domain objects at all (vs Surrounded, where you have to "include surrounded" in them).  
3. For this reason, Casting can be considered more of a library approach, vs Surrounded, which might be considered more of a framework approach.  That is, if you use Surrounded on a project, "Surrounded" stuff is going to be in both your domain objects and your use-case objects/modules.  With Casting, it's not *really* in either, other than a few calls to `cast_as`
4. The flip side of point 3: With surrounded, you get more sugar and convenience methods that clearly map to the higher level concepts of DCI.

Is this all fair?  Anything I'm missing?

**Comment by saturnflyer** [comment]
I use both of these libraries. I hope to make some videos about how they work and want the differences are.

1) Your first point is true. Using Casting previously would require a bit of work to get things going in a way similar to Surrounded but I've pushed some changes that might interest you. More on that in a bit...

2 & 3) I try as hard as possible to make a small buy-in and reasonably allow you to implement things differently if you like.
Surrounded has many places to override the default behavior and provide your own ideas, but it also provides a lot of good options to try.
With Casting, you still need to `include Casting::Client` in order to use it. That only adds some methods like `cast` (aliased to `delegate` if that method doesn't already exist) which executes behavior on an object immediately when called.
What Surrounded provides is the building blocks for a context object: that is to say, it's more like a framework for building objects with a specific runtime relationship to each other. Casting, on the other hand, provides tools for adding behavior to objects.
Surrounded also adds behavior to objects, but the main goal is to create the contexts.
Even with Casting, your objects still need to `include Casting::Client` and it will use `method_missing` on those objects to automatically use behavior **only** if you opt-in to that by using `delegate_missing_methods`.
You can use Casting without using `method_missing`.
Surrounded, however, mostly relies on `method_missing` and is a must in your domain objects _only_ in certain styles. You can for example implement role behavior in Surrounded using `wrapper` or `interface` which are an objects that handle `method_missing` allowing you to keep it out of your domain objects.

4) There's lots' of sugar in Surrounded for doing things in context objects. There's opt-in sugar in Casting for doing things in domain objects too. Using `method_missing` being one of them, but you can also opt-in to adding details about behaviors when getting a list of methods from an object. For example you can `include Casting::MethodConsolidator` in your domain object so that when you list all the known behavior for that object, it'll include those added by modules used by Casting: `object.methods #=> list of all methods defined in the object class AND those from the modules`

Your questions made me finally sit down to hammer out some ideas for using Casting to build Contexts.
This **requires** the use of refinements, so it's not required by default. See https://github.com/saturnflyer/casting/blob/master/examples/delegation_dci.rb and https://github.com/saturnflyer/casting/blob/master/lib/casting/context.rb
That also uses method_missing, but it's added as a refinement and I'll probably hack it to make that optional.

Feel free to ask anymore questions but bear with me if it takes a while for me to get back to you.

**Comment by jonahx** [comment]
Hey, just wanted to say thanks for the thorough reply, that cleared up a lot.  I think I will have followup questions, but need to sort out my thoughts and write them up.  Appreciate your time.  Jonah.
